version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: library_db  # This creates the database automatically
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: mongosh --eval "db.runCommand('ping').ok" -u admin -p password --quiet
      interval: 5s
      timeout: 30s
      retries: 3

  library-app:
    build: .
    container_name: library-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:password@mongodb:27017/library_db?authSource=admin&retryWrites=true&w=majority
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data: