version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin         # Same as SPRING_DATASOURCE_USERNAME
      POSTGRES_PASSWORD: password # Same as SPRING_DATASOURCE_PASSWORD
      POSTGRES_DB: library_db     # Database name
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]   # Health check for PostgreSQL
      interval: 5s
      timeout: 30s
      retries: 3

  library-app:
    build: .
    container_name: library-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/library_db
      SPRING_DATASOURCE_USERNAME: admin      # Same as POSTGRES_USER
      SPRING_DATASOURCE_PASSWORD: password  # Same as POSTGRES_PASSWORD
      SPRING_JPA_HIBERNATE_DDL_AUTO: update # Database schema handling
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
