services:
  - type: web
    name: library-app
    plan: free
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: library-db
          property: connectionString  # You need to ensure this points to the PostgreSQL connection string
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: library-db
          property: username  # The username for PostgreSQL
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: library-db
          property: password  # The password for PostgreSQL
    healthCheckPath: /actuator/health
